include: package:lints/recommended.yaml

analyzer:
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
    - '**/*.gr.dart'
  errors:
    missing_required_param: error
    missing_return: error
    unnecessary_getters_setters: warning

linter:
  rules:
    # Rules we want to disable
    avoid_print: false
    public_member_api_docs: false
    
    # Rules we want to enable
    prefer_final_fields: true
    use_key_in_widget_constructors: true
