// File generated by FlutterFire CLI + modificaciones manuales
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ANDROID (ya lo tienes)
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGU16hyf68d-eoRrjlQVkoLc3SZ5QzO5E',
    appId: '1:520125025244:android:4eb4196ebd912f2a5b1d19',
    messagingSenderId: '520125025244',
    projectId: 'prueba-tecnica-65e6e',
    storageBucket: 'prueba-tecnica-65e6e.firebasestorage.app',
  );

  // IOS (ya lo tienes)
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGU16hyf68d-eoRrjlQVkoLc3SZ5QzO5E',
    appId: '1:520125025244:ios:4eb4196ebd912f2a5b1d19',
    messagingSenderId: '520125025244',
    projectId: 'prueba-tecnica-65e6e',
    storageBucket: 'prueba-tecnica-65e6e.firebasestorage.app',
    iosBundleId: 'com.example.pruebaTecnica',
  );

  // WEB (AGREGA ESTA - usa tu configuración web)
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSTmCC01KJHoQTFkT_bNpHGSBdhXKJd7U',
    appId: '1:520125025244:web:0969067d503bd03d5b1d19',
    messagingSenderId: '520125025244',
    projectId: 'prueba-tecnica-65e6e',
    authDomain: 'prueba-tecnica-65e6e.firebaseapp.com',
    storageBucket: 'prueba-tecnica-65e6e.firebasestorage.app',
    measurementId: 'G-XXXXXXXXXX', // Si no tienes, omítelo
  );

  // LINUX (usa la misma de web con ajustes)
  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyBSTmCC01KJHoQTFkT_bNpHGSBdhXKJd7U', // Misma que web
    appId: '1:520125025244:web:0969067d503bd03d5b1d19', // Usa web
    messagingSenderId: '520125025244',
    projectId: 'prueba-tecnica-65e6e',
    storageBucket: 'prueba-tecnica-65e6e.firebasestorage.app',
  );

  // WINDOWS (igual que linux)
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSTmCC01KJHoQTFkT_bNpHGSBdhXKJd7U',
    appId: '1:520125025244:web:0969067d503bd03d5b1d19',
    messagingSenderId: '520125025244',
    projectId: 'prueba-tecnica-65e6e',
    storageBucket: 'prueba-tecnica-65e6e.firebasestorage.app',
  );

  // MACOS (usa la de iOS o web)
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGU16hyf68d-eoRrjlQVkoLc3SZ5QzO5E', // iOS o web
    appId: '1:520125025244:ios:4eb4196ebd912f2a5b1d19', // iOS
    messagingSenderId: '520125025244',
    projectId: 'prueba-tecnica-65e6e',
    storageBucket: 'prueba-tecnica-65e6e.firebasestorage.app',
    iosBundleId: 'com.example.pruebaTecnica',
  );
}